config/routes.rb
Bdquestoes::Application.routes.draw do
  resources :questoes

  resources :provas

  resources :turmas

end

app/models/prova.rb
class Prova < ActiveRecord::Base
	belongs_to :turma
	has_many :questoes
	
end

app/models/questao.rb
class Questao < ActiveRecord::Base
	belongs_to :prova
end

app/models/turma.rb
class Turma < ActiveRecord::Base
	has_many :provas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController
  # GET /provas
  # GET /provas.xml
  def index
    @provas = Prova.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @provas }
    end
  end

  # GET /provas/1
  # GET /provas/1.xml
  def show
    @prova = Prova.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prova }
    end
  end

  # GET /provas/new
  # GET /provas/new.xml
  def new
    @prova = Prova.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prova }
    end
  end

  # GET /provas/1/edit
  def edit
    @prova = Prova.find(params[:id])
  end

  # POST /provas
  # POST /provas.xml
  def create
    @prova = Prova.new(params[:prova])

    respond_to do |format|
      if @prova.save
        format.html { redirect_to(@prova, :notice => 'Prova was successfully created.') }
        format.xml  { render :xml => @prova, :status => :created, :location => @prova }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prova.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /provas/1
  # PUT /provas/1.xml
  def update
    @prova = Prova.find(params[:id])

    respond_to do |format|
      if @prova.update_attributes(params[:prova])
        format.html { redirect_to(@prova, :notice => 'Prova was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prova.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /provas/1
  # DELETE /provas/1.xml
  def destroy
    @prova = Prova.find(params[:id])
    @prova.destroy

    respond_to do |format|
      format.html { redirect_to(provas_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/questoes_controller.rb
class QuestoesController < ApplicationController
  # GET /questoes
  # GET /questoes.xml
  def index
    @questoes = Questao.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questoes }
    end
  end

  # GET /questoes/1
  # GET /questoes/1.xml
  def show
    @questao = Questao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @questao }
    end
  end

  # GET /questoes/new
  # GET /questoes/new.xml
  def new
    @questao = Questao.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @questao }
    end
  end

  # GET /questoes/1/edit
  def edit
    @questao = Questao.find(params[:id])
  end

  # POST /questoes
  # POST /questoes.xml
  def create
    @questao = Questao.new(params[:questao])

    respond_to do |format|
      if @questao.save
        format.html { redirect_to(@questao, :notice => 'Questao was successfully created.') }
        format.xml  { render :xml => @questao, :status => :created, :location => @questao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @questao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questoes/1
  # PUT /questoes/1.xml
  def update
    @questao = Questao.find(params[:id])

    respond_to do |format|
      if @questao.update_attributes(params[:questao])
        format.html { redirect_to(@questao, :notice => 'Questao was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @questao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questoes/1
  # DELETE /questoes/1.xml
  def destroy
    @questao = Questao.find(params[:id])
    @questao.destroy

    respond_to do |format|
      format.html { redirect_to(questoes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  # GET /turmas
  # GET /turmas.xml
  def index
    @turmas = Turma.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @turmas }
    end
  end

  # GET /turmas/1
  # GET /turmas/1.xml
  def show
    @turma = Turma.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @turma }
    end
  end

  # GET /turmas/new
  # GET /turmas/new.xml
  def new
    @turma = Turma.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @turma }
    end
  end

  # GET /turmas/1/edit
  def edit
    @turma = Turma.find(params[:id])
  end

  # POST /turmas
  # POST /turmas.xml
  def create
    @turma = Turma.new(params[:turma])

    respond_to do |format|
      if @turma.save
        format.html { redirect_to(@turma, :notice => 'Turma was successfully created.') }
        format.xml  { render :xml => @turma, :status => :created, :location => @turma }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @turma.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /turmas/1
  # PUT /turmas/1.xml
  def update
    @turma = Turma.find(params[:id])

    respond_to do |format|
      if @turma.update_attributes(params[:turma])
        format.html { redirect_to(@turma, :notice => 'Turma was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @turma.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.xml
  def destroy
    @turma = Turma.find(params[:id])
    @turma.destroy

    respond_to do |format|
      format.html { redirect_to(turmas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/questoes_helper.rb
module QuestoesHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Banco de Questoes</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/provas/_form.html.erb
<%= form_for(@prova) do |f| %>
  <% if @prova.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prova.errors.count, "error") %> prohibited this prova from being saved:</h2>

      <ul>
      <% @prova.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :turma_id %><br />
    
	<%= f.collection_select(:turma_id, 
			Turma.all,
			:id, :nome, options ={:prompt => false}) %>
	
  </div>
  <div class="field">
    <%= f.label :materia %><br />
    <%= f.text_field :materia %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provas/edit.html.erb
<h1>Editing prova</h1>

<%= render 'form' %>

<%= link_to 'Show', @prova %> |
<%= link_to 'Back', provas_path %>

app/views/provas/index.html.erb
<h1>Listing provas</h1>

<table>
  <tr>
    <th>Turma</th>
    <th>Materia</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @provas.each do |prova| %>
  <tr>
    <td><%= prova.turma_id %></td>
    <td><%= prova.materia %></td>
    <td><%= prova.data %></td>
    <td><%= link_to 'Show', prova %></td>
    <td><%= link_to 'Edit', edit_prova_path(prova) %></td>
    <td><%= link_to 'Destroy', prova, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo', new_prova_path %>

app/views/provas/new.html.erb
<h1>New prova</h1>

<%= render 'form' %>

<%= link_to 'Back', provas_path %>

app/views/provas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Turma:</b>
  <%= @prova.turma_id %>
</p>

<p>
  <b>Materia:</b>
  <%= @prova.materia %>
</p>

<p>
  <b>Data:</b>
  <%= @prova.data %>
</p>


<%= link_to 'Edit', edit_prova_path(@prova) %> |
<%= link_to 'Back', provas_path %>

app/views/questoes/_form.html.erb
<%= form_for(@questao) do |f| %>
  <% if @questao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@questao.errors.count, "error") %> prohibited this questao from being saved:</h2>

      <ul>
      <% @questao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prova_id %><br />
    
	<%= f.collection_select(:prova_id, 
		Prova.all,
		:id, :materia, options ={:prompt => false}) %>

  </div>
  <div class="field">
    <%= f.label :pergunta %><br />
    <%= f.text_field :pergunta %>
  </div>
  <div class="field">
    <%= f.label :resposta %><br />
    <%= f.text_field :resposta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questoes/edit.html.erb
<h1>Editing questao</h1>

<%= render 'form' %>

<%= link_to 'Show', @questao %> |
<%= link_to 'Back', questoes_path %>

app/views/questoes/index.html.erb
<h1>Listing questoes</h1>

<table>
  <tr>
    <th>Prova</th>
    <th>Pergunta</th>
    <th>Resposta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questoes.each do |questao| %>
  <tr>
    <td><%= questao.prova_id %></td>
    <td><%= questao.pergunta %></td>
    <td><%= questao.resposta %></td>
    <td><%= link_to 'Show', questao %></td>
    <td><%= link_to 'Edit', edit_questao_path(questao) %></td>
    <td><%= link_to 'Destroy', questao, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Questao', new_questao_path %>

app/views/questoes/new.html.erb
<h1>New questao</h1>

<%= render 'form' %>

<%= link_to 'Back', questoes_path %>

app/views/questoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prova:</b>
  <%= @questao.prova_id %>
</p>

<p>
  <b>Pergunta:</b>
  <%= @questao.pergunta %>
</p>

<p>
  <b>Resposta:</b>
  <%= @questao.resposta %>
</p>


<%= link_to 'Edit', edit_questao_path(@questao) %> |
<%= link_to 'Back', questoes_path %>

app/views/turmas/_form.html.erb
<%= form_for(@turma) do |f| %>
  <% if @turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% @turma.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing turma</h1>

<%= render 'form' %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<h1>Listing turmas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @turmas.each do |turma| %>
  <tr>
    <td><%= turma.nome %></td>
    <td><%= link_to 'Show', turma %></td>
    <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
    <td><%= link_to 'Destroy', turma, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New turma</h1>

<%= render 'form' %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @turma.nome %>
</p>


<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>